# Generated by Django 5.0.6 on 2024-07-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_book_author_book_is_bestseling_alter_book_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_bestseling',
            new_name='is_bestselling',
        ),
    ]
